---
title: "Organelle Analysis - Advanced Metrics - memory saver version"
author: "Fiona M. Love"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(terra)
library(ggplot2)#for cut functions, not graphing

```


Copied from Organelle_analysis_ImageJ_metrics.Rmd first - remove when combining
```{r}
dir <- choose.dir()
files <- list.files(dir, pattern = ('\\.csv$|\\.zip$'), recursive = FALSE, include.dirs = FALSE)
files <- files[-which(grepl('\\_ALL\\_CELL\\_ROIs\\.zip$|\\_ALL\\_ORGANELLE\\_ROIs\\.zip$', files))]
condcells <- unique(gsub('_results.csv||_POOLED_results.csv||_POOLED_ROIs.zip||_ROIs.zip||_summary_results.csv||_slice_labels.csv', '', files))#updated for cell-by-cell processing

setClass("Measurements", slots = c(data = "data.frame", cells = "data.frame", other = "data.frame"))

#measurements cleaning/categories
process_measurements <- function(dir, condition, file_pattern){
  df <- read.csv(paste0(dir, '\\', condition, file_pattern))
  df$ROI_name <- unlist(regmatches(df$Label, regexec("(?<=:).+(?=:)?", df$Label, perl = T)))
  #TODO - this might break if trailing : missing - dependent on single/multi channel image - should be consistent with macro
  df.cells = df[df$Type == 'cells',]
  df.other = df[df$Type != 'cells',]
  mes <- new("Measurements", data = df, cells = df.cells, other = df.other)
  return(mes)
}

pooled_measurements <- lapply(condcells, function(c){process_measurements(dir, c, "_POOLED_results.csv")})
names(pooled_measurements) <- condcells
```


Constants and functions
```{r}
slicenames.df <- read.csv(paste0(dir, '\\', condcells[1], '_slice_labels.csv'), header = FALSE)#running ONCE - should be consistent across batch
slicenames <- slicenames.df[,2]
organelles <- slicenames.df[slicenames.df$V3!='',2]
contacts <- slicenames.df[slicenames.df$V3=='',2]
contacts <- contacts[which(contacts != 'cell')]
contacts.components <- lapply(contacts, function(c){
  o <- strsplit(c, '')[[1]]
  org <- slicenames.df[slicenames.df$V3 %in% o, 2]
  return(org)
})
names(contacts.components) <- contacts


px_round <- function(x,y){
  xr <- round(x, digits = 0)
  yr <- round(y, digits = 0)
  if((x-xr)<0){ xr <- xr - 0.5 }
  else if((x-xr)>=0){ xr <- xr + 0.5 }
  if((y-yr)<0){ yr <- yr - 0.5 }
  else if((y-yr)>=0){ yr <- yr + 0.5 }
  return(c(xr, yr))
}

adv_metrics <- data.frame(
  condcell = condcells
)

norm_values <- data.frame(
  organelles = contacts
)

cent_type <- ifelse('nuclei' %in% slicenames, 'nuclei', 'cells')

binangle = 5 #degree width of bins for asymmetry coefficient - MUST SPLIT 360 INTO EVEN NUMBER OF GROUPS - e.g. 7 or 8 won't work
if((360/binangle) %% 2 != 0){ warning("Binangle must divide 360 into an even number of groups for the following code to work.") }
```

```{r}

for(c in condcells){
  print(paste0('Processing condition ', c))
  cell.raster <- rast(paste0(dir, '\\', c, '_stack.tif'))
  names(cell.raster) <- slicenames
  crs(cell.raster) <- 'local' #IMPORTANT - treat as planar coordinates instead of lon/lat
  
  cell.pixels <- as.data.frame(cell.raster, xy = TRUE) %>% filter(cell >0)
  
  p <- pooled_measurements[[c]]@data
  cell_cent <- p[p$Type == cent_type, c('X', 'Y')]
  remove(p)

  cell.pixels$dist_to_cent <- abs(sqrt((cell.pixels$x - cell_cent$X[1])^2 + (cell.pixels$y - cell_cent$Y[1])^2))
  cell.pixels$angle_to_cent <- (atan2((cell.pixels$y - cell_cent$Y[1]), (cell.pixels$x - cell_cent$X[1]))*180)/pi
  cell.pixels$anglebin <- cut_width(cell.pixels$angle_to_cent, width = binangle, closed = 'left', boundary = 0)
  
  cell.raster <- extend(cell.raster, c(1,1), fill = 0)
  cr <- subst(cell.raster[['cell']], 255, NA)
  
  cell.pixels$dist_to_PM <- as.data.frame(mask(distance(cr, exclude = 255), cell.raster[['cell']], maskvalues = 0))[,1]#distance to nearest PM pixel (outside cell)
  cell.pixels$cent_norm <- cell.pixels$dist_to_cent/(cell.pixels$dist_to_cent + cell.pixels$dist_to_PM)
  
  if('nuclei' %in% names(cell.raster)){
    cell.pixels$dist_to_nucleus = as.data.frame(mask(distance(cell.raster[['nuclei']], target = 0), cell.raster[['cell']], maskvalues = 0))[,1]#distance to nearest nucleus pixel (0 if overlapping)
    cell.pixels$nuc_norm <- cell.pixels$dist_to_nucleus/(cell.pixels$dist_to_nucleus + cell.pixels$dist_to_PM)
  }
  
  # for(o in slicenames[slicenames != 'cell']){
  #   adv_metrics[which(adv_metrics$condcell == c), paste0(o, '_MDR')] <- mean(cell.pixels[cell.pixels[,o]>0,]$norm)
  # }
  for(o in slicenames){#including cell here - might normalise to cell asymmetry downstream
    df.org <- cell.pixels[cell.pixels[o] > 0,]
    
    #MDR  
    adv_metrics[which(adv_metrics$condcell == c), paste0(o, '_centroid_MDR')] <- mean(df.org$cent_norm)
    if('nuclei' %in% names(cell.raster)){
      adv_metrics[which(adv_metrics$condcell == c), paste0(o, '_nucleus_MDR')] <- mean(df.org$nuc_norm)
    }
    
    #coefficient of asymmetry
    tab <- as.data.frame(table(df.org$anglebin))
    tally <- 0
    halfcount <- nrow(tab)/2
    for(n in 1:halfcount){
      a <- abs(tab[n, 'Freq'] - tab[n + halfcount, 'Freq'])
      tally <- tally + a
    }
    CoA <- tally/nrow(df.org)
    adv_metrics[which(adv_metrics$condcell == c), paste0(o, '_CoA')] <- CoA
    
    if (o %in% contacts){
      #pixel counts for normalising contact areas
      o.components <- contacts.components[[o]]
      pix <- nrow(cell.pixels %>% filter(if_any(matches(o.components), ~.>0)))
      norm_values[norm_values$organelles == o, c] <- pix
    }
    
  }
  
  remove(cell.raster)
  remove(cell.pixels)
  remove(cell_cent)
}

```


Combining with the other metrics
```{r}
full_metrics <- dplyr::left_join(metrics, adv_metrics, by = join_by(condcell == condcell))
```

Normalising contact areas to areas of involved organelles
```{r}
for(c in contacts){
  full_metrics[paste0(c, '_area_norm')] <- 
}
```


