---
title: "Organelle Analysis - Advanced Metrics"
author: "Fiona M. Love"
date: "2025-05-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(terra)
library(ggplot2)#for cut functions, not graphing
# library(stringr)

```


Copied from Organelle_analysis_ImageJ_metrics.Rmd first - remove when combining
```{r}
dir <- choose.dir()
files <- list.files(dir, pattern = ('\\.csv$|\\.zip$'), recursive = FALSE, include.dirs = FALSE)
files <- files[-which(grepl('\\_ALL\\_CELL\\_ROIs\\.zip$|\\_ALL\\_ORGANELLE\\_ROIs\\.zip$', files))]
condcells <- unique(gsub('_results.csv||_POOLED_results.csv||_POOLED_ROIs.zip||_ROIs.zip||_summary_results.csv||_slice_labels.csv', '', files))#updated for cell-by-cell processing

setClass("Measurements", slots = c(data = "data.frame", cells = "data.frame", other = "data.frame"))

#measurements cleaning/categories
process_measurements <- function(dir, condition, file_pattern){
  df <- read.csv(paste0(dir, '\\', condition, file_pattern))
  df$ROI_name <- unlist(regmatches(df$Label, regexec("(?<=:).+(?=:)?", df$Label, perl = T)))
  #TODO - this might break if trailing : missing - dependent on single/multi channel image - should be consistent with macro
  df.cells = df[df$Type == 'cells',]
  df.other = df[df$Type != 'cells',]
  mes <- new("Measurements", data = df, cells = df.cells, other = df.other)
  return(mes)
}

pooled_measurements <- lapply(condcells, function(c){process_measurements(dir, c, "_POOLED_results.csv")})
names(pooled_measurements) <- condcells
```


Reading in TIF stacks for each cell and creating pixel tables
```{r}
slicenames.df <- read.csv(paste0(dir, '\\', condcells[1], '_slice_labels.csv'), header = FALSE)#running ONCE - should be consistent across batch
slicenames <- slicenames.df[,2]
#TODO - 'core organelles' specified in CSV - hardcoding for now to test
organelles <- slicenames.df[slicenames.df$V3!='',2]
contacts <- slicenames.df[slicenames.df$V3=='',2]
contacts <- contacts[which(contacts != 'cell')]
contacts.components <- lapply(contacts, function(c){
  o <- strsplit(c, '')[[1]]
  org <- slicenames.df[slicenames.df$V3 %in% o, 2]
  return(org)
})
names(contacts.components) <- contacts


cells.rasters <- lapply(condcells, function(c){ 
  r <- rast(paste0(dir, '\\', c, '_stack.tif'))
  names(r) <- slicenames
  r <- extend(r, c(1,1), fill = 0)
  crs(r) <- 'local' #IMPORTANT - treat as planar coordinates instead of lon/lat
  return(r)
})
names(cells.rasters) <- condcells

cells.pixels <- lapply(cells.rasters, function(cr){
  as.data.frame(cr, xy = TRUE)
})
names(cells.pixels) <- condcells
```





MDR analysis
```{r}
#-----extract centroid - nuclei or cell-based------
#nucleus centroid
cent_type = ''
if('nuclei' %in% slicenames){
  cells.nuc_cent <- do.call(rbind, lapply(condcells, function(c){ 
    p <- pooled_measurements[[c]]@data
    cent <- p[p$Type == 'nuclei', c('X', 'Y')]#should only have one row in pooled measurements - combined centroid if multiples
    cent$condcell <- c
    return(cent)
  }))
  cent_type <- 'nuclei'
  cells.cent <- cells.nuc_cent
} else {#cell centroid
  cells.cell_cent <- do.call(rbind, lapply(condcells, function(c){
    p <- pooled_measurements[[c]]@data
    cent <- p[p$Type == 'cells', c('X', 'Y')]
    cent$condcell <- c
    return(cent)
  }))  
  cent_type <- 'cell'
  cells.cent  <- cells.cell_cent
}
#--------------------------
```

```{r}
#rounding centroids to nearest pixel coordinates
px_round <- function(x,y){
  xr <- round(x, digits = 0)
  yr <- round(y, digits = 0)
  if((x-xr)<0){ xr <- xr - 0.5 }
  else if((x-xr)>=0){ xr <- xr + 0.5 }
  if((y-yr)<0){ yr <- yr - 0.5 }
  else if((y-yr)>=0){ yr <- yr + 0.5 }
  return(c(xr, yr))
}
cells.cent.pixels <- do.call(rbind, lapply(1:nrow(cells.cent), function(i){#not using anywhere?
  row <- cells.cent[i,]
  px <- px_round(row$X, row$Y)
  df <- data.frame(x = px[1], y = px[2])
}))

```

```{r}
#efficiency - filter down to pixels inside cell boundary
for(name in names(cells.pixels)){
  cells.pixels[[name]] <- cells.pixels[[name]] %>% filter(cell != 0|is.na(cell))#prev. >0
}

binangle = 5 #degree width of bins for asymmetry coefficient - MUST SPLIT 360 INTO EVEN NUMBER OF GROUPS - e.g. 7 or 8 won't work
if((360/binangle) %% 2 != 0){ warning("Binangle must divide 360 into an even number of groups for the following code to work.") }

norm_values <- data.frame(
  organelles = contacts
)
```

```{r}
#-----calculate angles and distances for MDR/CoA/etc.-----
for(name in names(cells.pixels)){
  cell <- cells.pixels[[name]]
  #distance to nucleus/PM and standard MDR
  cent <- cells.cent[cells.cent$condcell == name,][1,]
  
  cell$dist_to_cent <- abs(sqrt((cell$x - cent$X)^2 + (cell$y - cent$Y)^2))
  cell$angle_to_cent <- (atan2((cell$y - cent$Y), (cell$x - cent$X))*180)/pi
  
  #asymmetry values
  cell$anglebin <- cut_width(cell$angle_to_cent, width = binangle, closed = 'left', boundary = 0)
  # cell$anglebin_left <- as.integer(str_match(as.character(cell$anglebin), '\\[(-?\\d+)\\,')[,2])
  # cell$anglebin_flipped <- sapply(cell$anglebin_left, function(i){ if(i < 0){ 0-(180-abs(i)) } else{ i } })
  
  cr <- subst(cells.rasters[[name]][['cell']], 255, NA)#cell raster
  #cytor <- subst(cells.rasters[[name]][['cell']]-cells.rasters[[name]][['nuclei']], 255, NA)#cytoplasm raster
  
  cell$dist_to_PM = as.data.frame(mask(distance(cr, exclude = 255), cells.rasters[[name]][['cell']], maskvalues = 0))[,1]#distance to nearest PM pixel (outside cell)
  cell$dist_to_NE = as.data.frame(mask(distance(cells.rasters[[name]][['nuclei']], target = 0), cells.rasters[[name]][['cell']], maskvalues = 0))[,1]
 #distance to nearest nucleus pixel (NOT EDGE OF NUCLEUS)
  
  cell$norm = cell$dist_to_cent/(cell$dist_to_cent + cell$dist_to_PM)
  cell$NE_norm = cell$dist_to_NE/(cell$dist_to_NE + cell$dist_to_PM)
  
  #TODO - calculate and compare to above values
  # cell$grid_to_cent
  # cell$grid_to_PM
  # cell$grid_norm
  
  #normalisation values for contact sites (total organelle areas)
  for(o in contacts){#NOT WORKING - LOOP CELLS
  #pixel counts for normalising contact areas
    o.components <- contacts.components[[o]]
    pix <- nrow(cell.pixels %>% filter(if_any(any_of(o.components), ~.!=0)))
    norm_values[norm_values$organelles == o, name] <- pix
}
  
  cells.pixels[[name]] <- cell
}


```

Mean MDR per organelle/contact type (averages over number of pixels in each)
```{r}
adv_metrics <- data.frame(
  condcell = condcells
)
for(o in slicenames[slicenames != 'cell']){
  adv_metrics[paste0(o, '_MDR')] <- sapply(condcells, function(c){ mean(cells.pixels[[c]][cells.pixels[[c]][o]>0,]$norm) })
  adv_metrics[paste0(o, '_NE_MDR')] <- sapply(condcells, function(c){ mean(cells.pixels[[c]][cells.pixels[[c]][o]>0,]$NE_norm) })
}
```

Asymmetry
```{r}
for(o in slicenames){
  adv_metrics[paste0(o, '_CoA')] <- sapply(condcells, function(c){ 
      df <- cells.pixels[[c]]
      df.org <- df[df[o] > 0,]
      tab <- as.data.frame(table(df.org$anglebin))
      tally = 0
      halfcount <- nrow(tab)/2
      for(n in 1:halfcount){
        a <- abs(tab[n, 'Freq'] - tab[n + halfcount, 'Freq'])
        tally <- tally + a
      }
      CoA <- tally/nrow(df.org)
      return(CoA)
    })
}
```

Contact site normalisation
```{r}


```


Contact (overlap) metrics
```{r}


```

Combining with the other metrics
```{r}
full_metrics <- dplyr::left_join(metrics, adv_metrics, by = join_by(condcell == condcell))
```


